font_family JetBrains Mono
font_size 15.0

background_opacity 0.6

color0  #000000
color8  #4d4d4d
color1  #ff5774
color9  #ff6580
color2  #6ae98a
color10 #70f893
color3  #ffe099
color11 #ffe6ad
color4  #ff7a99
color12 #ff8ba6
color5  #e0b2a5
color13 #e8c4bb
color6  #efdaa1
color14 #ffe8ac
color7  #bfbfbf
color15 #e6e6e6

map kitty_mod+f5  load_config_file
map ctrl+alt+c        copy_to_clipboard
map ctrl+alt+v        paste_from_clipboard
