font_family JetBrains Mono
font_size 16.0
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0

background_opacity 0.95
dynamic_background_opacity yes

# COLORS
foreground            #d0d0d5
background            #141416
selection_foreground  #ffffff
selection_background  #3a3a42
cursor                #ff4d4d
cursor_text_color     #141416

# Black / Gray
color0  #1d1d21
color8  #52525e

# Red (Ember / Crimson)
color1  #e63946
color9  #ff4d4d

# Green (Muted Sage)
color2  #6c8e74
color10 #8ba893

# Yellow (Ash Amber)
color3  #d08770
color11 #e59882

# Blue (Slate Steel)
color4  #5f789e
color12 #7a94ba

# Magenta (Dusky Rose)
color5  #a37ea0
color13 #c299be

# Cyan (Pale Frost)
color6  #689d9a
color14 #81b8b5

# White / Ash
color7  #b8b8c0
color15 #ededf2

map kitty_mod+f5      load_config_file
map ctrl+alt+c        copy_to_clipboard
map ctrl+alt+v        paste_from_clipboard
