# Remap leader key
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -as terminal-features ",*:RGB"

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set -g renumber-windows on

# Vim-like navigation keybinds
bind -N 'Select the pane above the active pane (custom)' -r k select-pane -U
bind -N 'Select the pane below the active pane (custom)' -r j select-pane -D
bind -N 'Select the pane to the left of the active pane (custom)' -r h select-pane -L
bind -N 'Select the pane to the right of the active pane (custom)' -r l select-pane -R
bind -N 'Select the previously current window (custom)' u last-window
bind -N 'Switch to the last client (custom)' U switch-client -l
bind -N 'Move the visible part of the window up (custom)' -r K refresh-client -U 10
bind -N 'Move the visible part of the window down (custom)' -r J refresh-client -D 10
bind -N 'Move the visible part of the window left (custom)' -r H refresh-client -L 10
bind -N 'Move the visible part of the window right (custom)' -r L refresh-client -R 10
bind -N 'Resize the pane up by 5 (custom)' -r M-k resize-pane -U 5
bind -N 'Resize the pane down by 5 (custom)' -r M-j resize-pane -D 5
bind -N 'Resize the pane left by 5 (custom)' -r M-h resize-pane -L 5
bind -N 'Resize the pane right by 5 (custom)' -r M-l resize-pane -R 5
bind -N 'Resize the pane up (custom)' -r C-k resize-pane -U
bind -N 'Resize the pane down (custom)' -r C-j resize-pane -D
bind -N 'Resize the pane left (custom)' -r C-h resize-pane -L
bind -N 'Resize the pane right (custom)' -r C-l resize-pane -R

# Tmux Statusbar
set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha
set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "yes"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# set default shell
set-option -g default-shell /usr/bin/zsh

# Initialize plugin manager
run '~/.tmux/plugins/tpm/tpm'
